# Problem Statement:- 
### Implement Artificial Neural Network training process in Python by using Forward Propagation, Back Propagation.

In [1]:
import numpy as np

In [2]:
X1 = np.array([[1, -1, 1, -1]])
X2 = np.array([[-1, -1, 1, 1]])
X3 = np.array([[1, 1, -1, -1]])
X4 = np.array([[1, 1, 1, 1]])



# X1 = np.array([[1, 1, 1, 1, 1, 1]])
# X2 = np.array([[-1, -1, -1, -1, -1, -1]])
# X3 = np.array([[1, -1, -1, 1, 1, 1]])
# X4 = np.array([[1, 1, -1, -1, -1, -1]])

X=[X1, X2, X3, X4]

Y1 = np.array([[1 ,0 ,1]])
Y2 = np.array([[1, 1, 1]])
Y3 = np.array([[0, 1, 1]])
Y4 = np.array([[1, 1, 0]])

# Y1 = np.array([[1, 1, 1]])
# Y2 = np.array([[-1, -1, -1]])
# Y3 = np.array([[-1, 1, 1]])
# Y4 = np.array([[1, -1, 1]])


Y= [Y1, Y2, Y3, Y4]

In [3]:
def calcWeight(X, Y):
    return np.dot(X.T, Y)

In [4]:
def weights(X,Y):
    weis=[]
    for i in range(4):
        weis.append(calcWeight(X[i], Y[i]))
    print(weis)
    return weis

In [5]:
weis=weights(X,Y)

[array([[ 1,  0,  1],
       [-1,  0, -1],
       [ 1,  0,  1],
       [-1,  0, -1]]), array([[-1, -1, -1],
       [-1, -1, -1],
       [ 1,  1,  1],
       [ 1,  1,  1]]), array([[ 0,  1,  1],
       [ 0,  1,  1],
       [ 0, -1, -1],
       [ 0, -1, -1]]), array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0]])]


In [6]:
def forward_aggregation(X,W):
    result=[]
    for i in range(len(X)):
        result.append(X[i]@W[i])
    return np.squeeze(result)

In [7]:
def activation(X):
    X = np.array(X)
    X[X > 0] = 1
    X[X == 0] = 0
    X[X < 0] = -1
    return X

In [8]:
for_aggri = forward_aggregation(X, weis)

In [9]:
for_aggri

array([[4, 0, 4],
       [4, 4, 4],
       [0, 4, 4],
       [4, 4, 0]])

In [10]:
print(activation(for_aggri))

[[1 0 1]
 [1 1 1]
 [0 1 1]
 [1 1 0]]


In [11]:
def backward_aggregation(X,W):
    result=[]
    for i in range(len(X)):
        result.append(W[i]@X[i].T)
    return np.squeeze(result)

In [12]:
back_aggri = backward_aggregation(Y, weis)

In [13]:
back_aggri

array([[ 2, -2,  2, -2],
       [-3, -3,  3,  3],
       [ 2,  2, -2, -2],
       [ 2,  2,  2,  2]])

In [14]:
print(activation(back_aggri))

[[ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]
 [ 1  1  1  1]]


# ____________________________________________________________

In [15]:
#inputs

X1 = np.array([[1,-1,1,-1]])
X2 = np.array([[-1,-1,1,1]])
X3 = np.array([[1,1,-1,-1]])
X4 = np.array([[1,1,1,1]])

X = [X1,X2,X3,X4]

Y1 = np.array([[1,0,1]])
Y2 = np.array([[1,1,1]])
Y3 = np.array([[0,1,1]])
Y4 = np.array([[1,1,0]])


Y = [Y1,Y2,Y3,Y4]

In [16]:
def calcweight(X,Y):
    return np.dot(X.T,Y)


In [17]:
def Weightss(X,Y):
    weigh = []
    for i in range(len(X)):
        weigh.append(calcweight(X[i],Y[i]))
        
    return weigh

In [18]:
weigh = Weightss(X,Y)

In [19]:
print(weigh)

[array([[ 1,  0,  1],
       [-1,  0, -1],
       [ 1,  0,  1],
       [-1,  0, -1]]), array([[-1, -1, -1],
       [-1, -1, -1],
       [ 1,  1,  1],
       [ 1,  1,  1]]), array([[ 0,  1,  1],
       [ 0,  1,  1],
       [ 0, -1, -1],
       [ 0, -1, -1]]), array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0]])]


In [20]:
#Forword Propagation

def Forword_propagation(X,W):
    result = []
    for i in range(len(X)):
        result.append(X[i]@W[i])
    return np.squeeze(result)


In [21]:
def Activation(X):
    X = np.array(X)
    X[X > 0] = 1
    X[X == 0] = 0
    X[X < 0] = -1
    
    return X

In [22]:
for_agg = Forword_propagation(X,weigh)

In [23]:
print(Activation(for_agg))

[[1 0 1]
 [1 1 1]
 [0 1 1]
 [1 1 0]]


In [24]:
# Backword Propagation


def Backword_aggregation(X,W):
    result = []
    for i in range(len(X)):
        result.append(W[i]@X[i].T)
    return np.squeeze(result)


In [25]:
back_agg = Backword_aggregation(Y,weigh)

In [26]:
print(Activation(back_agg))

[[ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]
 [ 1  1  1  1]]
