# Problem Statement:-
### Write a python program to illustrate ART neural network. 


In [1]:
import numpy as np

In [2]:
VP = 0.4
LR = 2

num_inputs = 4
num_clusters = 3

BU = np.full((num_inputs, num_clusters) , 1/(1+num_inputs))
TD = np.ones((num_clusters , num_inputs))


In [3]:
print(BU)

[[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]


In [4]:
print(TD)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
def ART(inputs):
    for p in range(4):
        s = inputs
        s_norm = sum(s)
        
        
        y1 = BU[0][0]*inputs[0] + BU[1][0]*inputs[1] + BU[2][0]*inputs[2]+ BU[3][0]*inputs[3]
        y2 = BU[0][1]*inputs[0] + BU[1][1]*inputs[1] + BU[2][1]*inputs[2]+ BU[3][1]*inputs[3]
        y3 = BU[0][2]*inputs[2] + BU[1][0]*inputs[2] + BU[2][2]*inputs[2]+ BU[3][2]*inputs[3]
        
        J =  0
        if(y1  > y2 and y1 > y3):
            J = 0
        elif(y2 > y1 and y2 > y3):
            J = 1
        elif(y3 > y1 and y3 > y2):
            J = 2
        elif(y1 == y2 and y2 == y3):
            J = 0
        
        x_matrix = []
        
        for i in range(len(s)):
            x_matrix.append(s[i]*TD[J][i])
        
        
        x_norm = sum(x_matrix)
        
        if(x_norm/s_norm > VP):
            BU[0][J] = (LR * x_matrix[0]) / (LR - 1 + x_norm)
            BU[1][J] = (LR * x_matrix[1]) / (LR - 1 + x_norm)
            BU[2][J] = (LR * x_matrix[2]) / (LR - 1 + x_norm)
            BU[3][J] = (LR * x_matrix[3]) / (LR - 1 + x_norm)
        
            TD[J][0] = BU[0][J]
            TD[J][1] = BU[1][J]
            TD[J][2] = BU[2][J]
            TD[J][3] = BU[3][J]
            
        
    return J
        

In [6]:
def test(inputs):
    s = inputs
    s_norm = sum(s)
    xx = sum(inputs)
    
    y1 = BU[0][0]*inputs[0] + BU[1][0]*inputs[1] + BU[2][0]*inputs[2]+ BU[3][0]*inputs[3]
    y2 = BU[0][1]*inputs[0] + BU[1][1]*inputs[1] + BU[2][1]*inputs[2]+ BU[3][1]*inputs[3]
    y3 = BU[0][2]*inputs[2] + BU[1][0]*inputs[2] + BU[2][2]*inputs[2]+ BU[3][2]*inputs[3]
        
    j = 0
    if(y1 > y2 and y1>y3):
            j=0
    elif(y2 > y1 and y2>y3):
            j=1  
    elif(y3 > y2 and y3>y1):
            j=2
    elif(y1==y2 and y2==y3):
            j=0
        
    return j
    

In [7]:
inputss = [[0,0,1,1],[0,0,1,0],[1,0,0,1],[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],[1,0,0,0],[0,0,0,1]]

In [8]:
for i in inputss:
    print(ART(i))

2
2
0
1
2
1
1
1
0
0


In [9]:
test([0,1,1,1])

1